### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by filmgarage** [dib0/elro_connects#3]
Any chance that this will once become a home assistant integration?

**Comment by dib0** [comment]
Very possibly. @hildensia is working on a better implementation (his python skills are far better than mine) and is thinking about creating a home assistant implementation. Check out pull requests #1 and #2. I haven't had time to dive into them, hopefully I can do that soon

**Comment by hildensia** [comment]
@filmgarage If you look into the PRs (or my fork in the `feature/mqtt` branch) the refactored version is actually functional with home assistant, since it includes an MQTT client. All alarms and updates are published as MQTT topic and you should be able to use the MQTT integration of home assistant to use those. However, I never tested it in such an integrated way. But it worked with `test.mosquitto.org` as broker. I will eventually integrate it in home assistant, but that may take a few more months.

**Comment by filmgarage** [comment]
Interesting! Home automation is still an expensive hobby and I think it would benefit a lot of people if it becomes affordable. I am convinced that home automation should improve the quality of living and safety. The ELRO smoke detectors would be a very welcome addition to the integrated smart home. I will keep an eye on your work and try to test your MQTT version.

**Comment by hildensia** [comment]
@filmgarage FYI, MQTT is now integrated in mainline, and also somewhat tested.
